### ISSUE TITLE
Hermes is useless without fork as long as github.com/Masterminds/sprig won't update it's package.

### ISSUE THREAD

**Issue by kerak19** [matcornic/hermes#36]
Title says that all.

**Comment by matcornic** [comment]
Can you explain better your context ? I don't understand why the Hermes library as a whole is useless because of some dependencies. 

Besides, sprig is not deprecated so I don't understand the issue. And finally, sprig is used mainly for users that want advanced functions in custom template themes. The provided themes currently use sprig only for its `replace` function.

What are you trying to do ? What can't you do because of *this* problem ?

**Comment by kerak19** [comment]
I cannot run application while using Hermes because of 
`
../../../../github.com/Masterminds/sprig/crypto.go:35:37: multiple-value uuid.NewV4() in single-value context`

**Comment by matcornic** [comment]
It's probably because your app or one of the dependencies uses version `1.2.0` of `uuid` package. So it's a incompatibility of transitive dependencies in `sprig`, not an `hermes` issue.

If you can (and want), a solution is to downgrade the version of `uuid` of your app to `1.1.0`. A better solution is to create an issue on Sprig repo and maybe [create a PR](https://github.com/Masterminds/sprig/blob/efda631a76d70875162cdc25ffa0d0164bf69758/crypto.go#L34).

Do you use `dep` or any other build tool to build your app ? Or do you use `go get` ?

**Comment by kerak19** [comment]
I know it's not Hermes issue, but Satori/sprig. Satori because of api breaking changes and sprig because of lack of update to new version. Unfortunately it also concerns Hermes. There are PR on sprig package, they're just not merged.
